### ISSUE TITLE
acessing socket from model

### ISSUE THREAD

**Issue by alienatorZ** [refucktor/loopback-component-socketio#1]
How do I use the socket.io component from my model? For example how could I do something like:

'use strict';

module.exports = function(asset) {
 socket.on('customEvent', function (data) {
     asset.updateSomething(data);
}) 
}

**Comment by refucktor** [comment]
This is a first rough version of what I would really want to create. Unfortunately, I'm quite busy now and I couldn't improve the code and increase the features.

So, here my proposal.
You need to be aware of accessing [loopback objecst](http://loopback.io/doc/en/lb3/Working-with-LoopBack-objects.html), after that io should be part your application object already, below you can see it.

```javascript
'use strict';

const app = require('../../server/server'); //Accessing to application object
const socket = app.io.;
module.exports = function(asset) {
    socket.on('customEvent', function (data) {
         asset.updateSomething(data);
   })
}
```

Let me know if it's working for you. feel free to improve the code and make a pull-request
